<?php
/*

To achieve this

online converter
then search all \$ and replace with \\$
then check for all double quotes in javascript strings and replace them with an extra two backslashes

$requiredPageUserLevel
$title
$entryText

$simple

if $simple
array of numbers required (tagBox)

if $complex
array of tagcategories required (tagBox)

*/



echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<?php require '../../includes/config.inc.php';?>\n";
echo "\n";
echo "\n";
echo "<head>\n";
echo "\n";
echo "    <?php\n";
echo "\n";
echo "//error_reporting(E_ALL);\n";
echo "\n";
echo "\n";
echo "      //define user access level\n";
echo "\n";
echo "      //\$openaccess = 1;\n";
echo "      \$requiredUserLevel = 6;\n";
echo "\n";
echo "\n";
echo "      require BASE_URI . '/head.php';\n";
echo "\n";
echo "      \$general = new general;\n";
echo "\n";
echo "      \$navigator = new navigator;\n";
echo "\n";
echo "      \$users = new users;\n";
echo "\n";
echo "      ?>\n";
echo "\n";
echo "    <!--Page title-->\n";
echo "    <title>GIEQs Online Endoscopy Trainer - Polypectomy Videos Preview</title>\n";
echo "\n";
echo "    <link rel=\"stylesheet\" href=\"<?php echo BASE_URL;?>/assets/libs/animate.css/animate.min.css\">\n";
echo "\n";
echo "\n";
echo "    <style>\n";
echo "       \n";
echo "        .gieqsGold {\n";
echo "\n";
echo "            color: rgb(238, 194, 120);\n";
echo "\n";
echo "\n";
echo "        }\n";
echo "\n";
echo "        .card-placeholder{\n";
echo "\n";
echo "            width: 344px;\n";
echo "\n";
echo "        }\n";
echo "\n";
echo "        .break {\n";
echo "  flex-basis: 100%;\n";
echo "  height: 0;\n";
echo "}\n";
echo "\n";
echo ".flex-even {\n";
echo "  flex: 1;\n";
echo "}\n";
echo "\n";
echo ".flex-nav {\n";
echo "  flex: 0 0 18%;\n";
echo "}\n";
echo "\n";
echo "\n";
echo "        \n";
echo "        .gieqsGoldBackground {\n";
echo "\n";
echo "background-color: rgb(238, 194, 120);\n";
echo "\n";
echo "\n";
echo "}\n";
echo "\n";
echo "        .tagButton {\n";
echo "\n";
echo "            cursor: pointer;\n";
echo "\n";
echo "        }\n";
echo "\n";
echo "        \n";
echo "\n";
echo "        \n";
echo "\n";
echo "        iframe {\n";
echo "  box-sizing: border-box;\n";
echo "    height: 25.25vw;\n";
echo "    left: 50%;\n";
echo "    min-height: 100%;\n";
echo "    min-width: 100%;\n";
echo "    transform: translate(-50%, -50%);\n";
echo "    position: absolute;\n";
echo "    top: 50%;\n";
echo "    width: 100.77777778vh;\n";
echo "}\n";
echo ".cursor-pointer {\n";
echo "\n";
echo "    cursor: pointer;\n";
echo "\n";
echo "}\n";
echo "\n";
echo "@media (max-width: 768px) {\n";
echo "\n";
echo "    .flex-even {\n";
echo "  flex-basis: 100%;\n";
echo "}\n";
echo "}\n";
echo "\n";
echo "@media (max-width: 768px) {\n";
echo "\n";
echo ".card-header {\n";
echo "    height:250px;\n";
echo "}\n";
echo "\n";
echo ".card-placeholder{\n";
echo "\n";
echo "    width: 204px;\n";
echo "\n";
echo "}\n";
echo "\n";
echo "\n";
echo "}\n";
echo "\n";
echo "@media (min-width: 1200px) {\n";
echo "        #chapterSelectorDiv{\n";
echo "\n";
echo "            \n";
echo "                \n";
echo "                top:-3vh;\n";
echo "            \n";
echo "\n";
echo "        }\n";
echo "        #playerContainer{\n";
echo "\n";
echo "                margin-top:-20px;\n";
echo "\n";
echo "        }\n";
echo "        #collapseExample {\n";
echo "\n";
echo "            position: absolute; \n";
echo "            max-width: 50vh; \n";
echo "            z-index: 25;\n";
echo "        }\n";
echo "\n";
echo "        \n";
echo "\n";
echo "}\n";
echo "    </style>\n";
echo "\n";
echo "\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "    <header class=\"header header-transparent\" id=\"header-main\">\n";
echo "\n";
echo "        <!-- Topbar -->\n";
echo "\n";
echo "        <?php require BASE_URI . '/pages/learning/includes/topbar.php';?>\n";
echo "\n";
echo "        <!-- Main navbar -->\n";
echo "\n";
echo "        <?php require BASE_URI . '/pages/learning/includes/nav.php';?>\n";
echo "\n";
echo "        \n";
echo "\n";
echo "\n";
echo "    </header>\n";
echo "\n";
echo "    <?php\n";
echo "		if (isset(\$_GET[\"id\"]) && is_numeric(\$_GET[\"id\"])){\n";
echo "			\$id = \$_GET[\"id\"];\n";
echo "		\n";
echo "		}else{\n";
echo "		\n";
echo "			\$id = null;\n";
echo "		\n";
echo "		}\n";
echo "				    \n";
echo "                        \n";
echo "                        \n";
echo "		\n";
echo "        ?>\n";
echo "        \n";
echo "        <!-- load all video data -->\n";
echo "\n";
echo "        <div id=\"id\" style=\"display:none;\"><?php if (\$id){echo \$id;}?></div>\n";
echo "\n";
echo "        <!--- specifiy the tag Categories required for display  CHANGEME-->\n";
echo "\n";
echo "        <?php\n";
echo "        \$requiredTagCategories = ['65'];\n";
echo "        \$requiredVideos = ['113', '114', '137'];\n";
echo "\n";
echo "        ?>\n";
echo "\n";
echo "        <div id=\"requiredTagCategories\" style=\"display:none;\"><?php echo json_encode(\$requiredTagCategories);?></div>\n";
echo "        <div id=\"requiredVideos\" style=\"display:none;\"><?php echo json_encode(\$requiredVideos);?></div>\n";
echo "\n";
echo "       \n";
echo "\n";
echo "                    <!--CONSTRUCT TAG DISPLAY-->\n";
echo "\n";
echo "                    <!--GET TAG CATEGORY NAME \n";
echo "                    \n";
echo "                    <?php\n";
echo "\n";
echo "                    //define the page for referral info\n";
echo "\n";
echo "                    //\$url =  \"//{\$_SERVER['HTTP_HOST']}{\$_SERVER['REQUEST_URI']}\";\n";
echo "                    \$url =  \"{\$_SERVER['REQUEST_URI']}\";\n";
echo "\n";
echo "                    \$escaped_url = htmlspecialchars( \$url, ENT_QUOTES, 'UTF-8' );\n";
echo "\n";
echo "                    ?>\n";
echo "-->\n";
echo "\n";
echo "        <div id=\"escaped_url\" style=\"display:none;\"><?php echo \$escaped_url;?></div>\n";
echo "\n";
echo "<!--\n";
echo "                    \n";
echo "                TODO see other videos with similar tags, see videos with this tag, tag jump the video,\n";
echo "                list of chapters with associated tags [toggle view by category, chapter]\n";
echo "                \n";
echo "                -->\n";
echo "\n";
echo "\n";
echo "    <!-- Omnisearch -->\n";
echo "   \n";
echo "    <div class=\"main-content bg-gradient-dark\">\n";
echo "\n";
echo "        <!--Header CHANGEME-->\n";
echo "\n";
echo "    <div class=\"d-flex flex-wrap container pt-10 mt-5\">\n";
echo "        <div class=\"h1 mr-auto\">Colorectal Polypectomy</div>\n";
echo "       <!--  <div class=\"w-50\"><?php //require(BASE_URI . '/pages/learning/pages/account/memberCard.php');?></div> -->\n";
echo "   \n";
echo "\n";
echo "    </div>\n";
echo "    <p class=\"h3 gieqsGold container \">A Primer</p>\n";
echo "\n";
echo "    <div class=\"d-flex align-items-end container\">\n";
echo "        <p class=\"text-muted pl-4 mt-2\">Below is a selection of lectures and interactive learning tools for those taking their first steps in colonoscopic polypectomy.</p>\n";
echo "\n";
echo "    </div>\n";
echo "\n";
echo "\n";
echo "        <!--Navigation-->\n";
echo "\n";
echo "    <div id=\"navigationZone\">\n";
echo "    <?php //require(BASE_URI . '/pages/learning/includes/navigation.php'); ?>\n";
echo "    </div>\n";
echo "    \n";
echo "\n";
echo "\n";
echo "        <!--Video Display-->\n";
echo "\n";
echo "\n";
echo "    <div class=\"container mt-4 pb-6\">\n";
echo "        <div id=\"videoCards\" class=\"flex-wrap\">\n";
echo "            \n";
echo "\n";
echo "            <div class=\"d-flex align-items-center\">\n";
echo "                <strong>Loading...</strong>\n";
echo "                <div class=\"spinner-border ml-auto\" role=\"status\" aria-hidden=\"true\"></div>\n";
echo "              </div>\n";
echo "            \n";
echo "  \n";
echo "\n";
echo "\n";
echo "        </div>\n";
echo "\n";
echo "    </div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "   \n";
echo "   \n";
echo "    \n";
echo "\n";
echo "       \n";
echo "    </div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "    \n";
echo "    <!-- Modal -->\n";
echo "    \n";
echo "\n";
echo "    <?php require BASE_URI . '/footer.php';?>\n";
echo "\n";
echo "    <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->\n";
echo "    <!-- <script src=\"assets/js/purpose.core.js\"></script> -->\n";
echo "    <!-- Page JS -->\n";
echo "     <!-- Google maps -->\n";
echo "    \n";
echo "    <!-- Purpose JS -->\n";
echo "    <script src=<?php echo BASE_URL . \"/assets/js/purpose.js\"?>></script>\n";
echo "    <!-- <script src=<?php echo BASE_URL . \"/assets/js/generaljs.js\"?>></script> -->\n";
echo "    <script>\n";
echo "    var videoPassed = \$(\"#id\").text();\n";
echo "                    </script>\n";
echo "\n";
echo "    <script src=<?php echo BASE_URL . \"/pages/learning/includes/social.js\"?>></script>\n";
echo "\n";
echo "    <script>\n";
echo "        \n";
echo "        //the number that are actually loaded\n";
echo "        var loaded = 1;\n";
echo "\n";
echo "        //the number the user wants\n";
echo "        var loadedRequired = 1;\n";
echo "\n";
echo "        var firstTime = 1; var activeStatus = 1;\n";
echo "\n";
echo "        var requiredTagCategoriesText = \$(\"#requiredTagCategories\").text();\n";
echo "\n";
echo "        var requiredTagCategories = JSON.parse(requiredTagCategoriesText);\n";
echo "        \n";
echo "        var requiredVideosText = \$(\"#requiredVideos\").text();\n";
echo "\n";
echo "        var requiredVideos = JSON.parse(requiredVideosText);\n";
echo "\n";
echo "\n";
echo "        function refreshNavAndTags(){\n";
echo "\n";
echo "            var screenTop = \$(document).scrollTop();\n";
echo "\n";
echo "            //console.log(top);\n";
echo "\n";
echo "            var tags = [];\n";
echo "\n";
echo "                \$('.tag').each(function(){\n";
echo "\n";
echo "                    if (\$(this).is(\":checked\")){\n";
echo "                        tags.push(\$(this).attr('data'));\n";
echo "                    }\n";
echo "\n";
echo "\n";
echo "                })\n";
echo "\n";
echo "                \n";
echo "\n";
echo "                //push how many loaded, use loaded variable\n";
echo "\n";
echo "                console.dir(tags);\n";
echo "\n";
echo "                /*var key = \$(this).attr('data');\n";
echo "\n";
echo "				const dataToSend = {\n";
echo "\n";
echo "					key: key,\n";
echo "\n";
echo "				}*/var dataToSend = {\n";
echo "\n";
echo "                    tags: tags,\n";
echo "                    requiredTagCategories: requiredTagCategories,\n";
echo "                    requiredVideos: requiredVideos,\n";
echo "                    active: activeStatus,\n";
echo "\n";
echo "                    }\n";
echo "\n";
echo "                    //const jsonString2 = JSON.stringify(dataToSend);\n";
echo "\n";
echo "				const jsonString = JSON.stringify(dataToSend);\n";
echo "				////console.log(jsonString);\n";
echo "				//console.log(siteRoot + \"/pages/learning/scripts/getNavv2.php\");\n";
echo "\n";
echo "				var request2 = \$.ajax({\n";
echo "					beforeSend: function () {\n";
echo "\n";
echo "                        \$('#videoCards').html(\"<div class=\\\"d-flex align-items-center\\\"><strong>Loading...</strong><div class=\\\"spinner-border ml-auto\\\" role=\\\"status\\\" aria-hidden=\\\true\\\"></div></div>\");\n";
echo "                        //for each tags array push the badges to the tags shown area\n";
echo "                        var html = '';\n";
echo "                        \$.each(tags, function(k,v){\n";
echo "\n";
echo "                            //HERE WE HAVE THE TAGID\n";
echo "                            \n";
echo "                            var tagid = v;\n";
echo "\n";
echo "                            //get the name and category\n";
echo "\n";
echo "                            var tagName = \$('body').find('#navigationZone').find('#tag'+v).siblings().text();\n";
echo "\n";
echo "                            var tagCategory = \$('body').find('#navigationZone').find('#tag'+v).parent().parent().parent().parent().find('span').text();\n";
echo "\n";
echo "                            html += '<span class=\"badge bg-gieqsGold text-dark mx-2 my-2 tagButton\" data=\"'+v+'\">'+tagCategory+ ' / ' +tagName+' <i style=\"float:right;\" class=\"fas fa-times removeTag cursor-pointer ml-1\" data=\"'+v+'\"></i></span>';\n";
echo "\n";
echo "                        });\n";
echo "                        \$('body').find('#navigationZone').find('#shown-tags').html(html);\n";
echo "\n";
echo "					},\n";
echo "					url: siteRoot + \"/pages/learning/scripts/getNavv2.php\",\n";
echo "					type: \"POST\",\n";
echo "					contentType: \"application/json\",\n";
echo "					data: jsonString,\n";
echo "				});\n";
echo "\n";
echo "\n";
echo "\n";
echo "				request2.done(function (data) {\n";
echo "                    // alert( \"success\" );\n";
echo "                    if (data != '[]'){\n";
echo "                        var toKeep = \$.parseJSON(data.trim());\n";
echo "                        //alert(data.trim());\n";
echo "                        console.dir(toKeep);\n";
echo "                        \n";
echo "                             \n";
echo "                            \$('.tag').each(function(){\n";
echo "\n";
echo "                                var tagid = \$(this).attr('data');\n";
echo "\n";
echo "                                if (toKeep.indexOf(tagid) > -1){\n";
echo "\n";
echo "                                    \$(this).attr('disabled', false);\n";
echo "\n";
echo "                                }else{\n";
echo "\n";
echo "                                    \$(this).attr('disabled', true);\n";
echo "                                }\n";
echo "\n";
echo "                            })    \n";
echo "\n";
echo "                      \n";
echo "                    }\n";
echo "					//\$(document).find('.Thursday').hide();\n";
echo "                })\n";
echo "                \n";
echo "                request2.then(function (data) {\n";
echo "                    var tags = [];\n";
echo "\n";
echo "                    \$('.tag').each(function(){\n";
echo "\n";
echo "                        if (\$(this).is(\":checked\")){\n";
echo "                            tags.push(\$(this).attr('data'));\n";
echo "                        }\n";
echo "\n";
echo "\n";
echo "                    })\n";
echo "\n";
echo "                    //TODO ADD ABILITY TO PASS A PARAMETER HERE INDICATING NUMBER LOADED\n";
echo "                    //THEN MODIFY LAYOUT AND NUMBER LOADED\n";
echo "\n";
echo "                    console.dir(tags);\n";
echo "\n";
echo "                    var dataToSend = {\n";
echo "\n";
echo "                        tags: tags,\n";
echo "                        loaded: loaded,\n";
echo "                        loadedRequired: loadedRequired,\n";
echo "                        requiredTagCategories: requiredTagCategories,\n";
echo "                        requiredVideos: requiredVideos,\n";
echo "                        referringUrl: \$('#escaped_url').text(), active: activeStatus,\n";
echo "\n";
echo "\n";
echo "\n";
echo "                    }\n";
echo "\n";
echo "                    const jsonString2 = JSON.stringify(dataToSend);\n";
echo "\n";
echo "                  \n";
echo "\n";
echo "                    \n";
echo "                    const jsonString = JSON.stringify(tags);\n";
echo "\n";
echo "                    console.dir(jsonString2);\n";
echo "\n";
echo "\n";
echo "                    var request3 = \$.ajax({\n";
echo "					beforeSend: function () {\n";
echo "\n";
echo "\n";
echo "					},\n";
echo "					url: siteRoot + \"/pages/learning/scripts/getVideosSimple.php\",\n";
echo "					type: \"POST\",\n";
echo "					contentType: \"application/json\",\n";
echo "					data: jsonString2,\n";
echo "                    });\n";
echo "                    request3.done(function (data) {\n";
echo "                    // alert( \"success\" );\n";
echo "                    if (data){\n";
echo "                        //var toKeep = \$.parseJSON(data.trim());\n";
echo "                        //alert(data.trim());\n";
echo "                        //console.dir(toKeep);\n";
echo "\n";
echo "                        \$('#videoCards').html(data);\n";
echo "                        \$('body').find('#itemCount').each(function(){\n";
echo "\n";
echo "                            var count = \$('body').find('.individualVideo').length;\n";
echo "                            \$(this).text(count);\n";
echo "\n";
echo "\n";
echo "                        })\n";
echo "\n";
echo "\n";
echo "                        if (firstTime == 1){\n";
echo "                        \$('body').on('click', '#loadMore', function () {\n";
echo "\n";
echo "                        loadedRequired = loadedRequired + 1;\n";
echo "\n";
echo "            \n";
echo "                        refreshNavAndTags();\n";
echo "\n";
echo "                        })\n";
echo "                        }\n";
echo "\n";
echo "                        \n";
echo "\n";
echo "                        if (firstTime > 1 && loadedRequired > 1){\n";
echo "\n";
echo "                                var loadedRequiredMultiple = ((loadedRequired-1) * 10)-3;\n";
echo "\n";
echo "                                //console.log(loadedRequiredMultiple);\n";
echo "\n";
echo "                                //scroll to current level\n";
echo "\n";
echo "                            \n";
echo "                                \$(\"body,html\").animate(\n";
echo "                                {\n";
echo "                                    scrollTop: \$('body').find('.individualVideo:eq('+loadedRequiredMultiple +')').offset().top\n";
echo "                                },\n";
echo "                                2 //speed\n";
echo "                                );\n";
echo "                        }\n";
echo "                       \n";
echo "                        \n";
echo "                        firstTime = firstTime + 1;\n";
echo "                        //\$('body').find('.individualVideo:eq('+loadedRequiredMultiple +')').scrollTop(300);\n";
echo "                        \n";
echo "                        \n";
echo "                               \n";
echo "\n";
echo "                      \n";
echo "                    }\n";
echo "					//\$(document).find('.Thursday').hide();\n";
echo "                })\n";
echo "\n";
echo "\n";
echo "				})\n";
echo "\n";
echo "\n";
echo "        }\n";
echo "\n";
echo "        \$(document).ready(function () {\n";
echo "\n";
echo "           \n";
echo "\n";
echo "            refreshNavAndTags();\n";
echo "\n";
echo "            \$('#refreshNavigation').click(function(){\n";
echo "\n";
echo "\n";
echo "                firstTime = 1;\n";
echo "                 //the number that are actually loaded\n";
echo "                loaded = 1;\n";
echo "\n";
echo "                //the number the user wants\n";
echo "                loadedRequired = 1;\n";
echo "                \n";
echo "                \$('.tag').each(function(){\n";
echo "\n";
echo "                    if (\$(this).is(\":checked\")){\n";
echo "                        \n";
echo "                        \$(this).prop('checked', false);\n";
echo "                    }\n";
echo "\n";
echo "\n";
echo "                })\n";
echo "\n";
echo "                refreshNavAndTags();\n";
echo "\n";
echo "            })\n";
echo "\n";
echo "            //on load check if any are checked, if so load the videos\n";
echo "\n";
echo "            //if none are checked load 10 most recent videos for these categories\n";
echo "\n";
echo "            \$('.tag').click(function(){\n";
echo "\n";
echo "                refreshNavAndTags();\n";
echo "\n";
echo "            })\n";
echo "\n";
echo "            \$('body').on('click', '.removeTag', function(){\n";
echo "\n";
echo "                var tagToRemove = \$(this).attr('data');\n";
echo "                //remove the check from the tag removed\n";
echo "\n";
echo "                \$('.tag').each(function(){\n";
echo "\n";
echo "                if (\$(this).attr(\"data\") == tagToRemove){\n";
echo "                    \n";
echo "                    \$(this).prop('checked', false);\n";
echo "\n";
echo "                }\n";
echo "\n";
echo "\n";
echo "                })\n";
echo "\n";
echo "\n";
echo "                refreshNavAndTags();\n";
echo "\n";
echo "            })\n";
echo "            //active behaviour\n";
echo "\n";
echo "            \$('body').on('change', '#active', function(){\n";
echo "\n";
echo "                var active = \$(this).children(\"option:selected\").val();\n";
echo "                //remove the check from the tag removed\n";
echo "\n";
echo "                activeStatus = active;\n";
echo "\n";
echo "                refreshNavAndTags();\n";
echo "\n";
echo "            })\n";
echo "\n";
echo "            \n";
echo "\n";
echo "\n";
echo "           \n";
echo "           \n";
echo "\n";
echo "         \n";
echo "\n";
echo "\n";
echo "        })\n";
echo "    </script>\n";
echo "</body>\n";
echo "\n";
echo "</html>";


?>
